import type { Metadata } from 'next';
import { Inter, Roboto, Montserrat } from 'next/font/google';
import './globals.scss';

// const inter = Inter({ subsets: ['latin'] });
// const roboto = Roboto({
//   weight: ['400', '700'],
//   style: ['normal', 'italic'],
//   subsets: ['latin'],
//   display: 'swap',
// });
const motserrat = Montserrat({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={motserrat.className}>
        {/* <header>
          <h1>Header</h1>
        </header> */}
        {children}
        {/* <footer>
          <h1>Footer</h1>
        </footer> */}
      </body>
    </html>
  );
}
